name: tranquility
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^8.0.1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  dio: ^5.4.2+1
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  clipboard: ^0.1.3
  camera: ^0.10.5+9
  lottie: ^3.1.0
  image_picker: ^1.0.8
  url_launcher: ^6.2.6
  flutter_screenutil: ^5.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: MyStery
      fonts:
        - asset: assets/fonts/mystery_quest.ttf
